pr: none
trigger:
  branches:
    include:
      - master

variables:
  - group: elarande-general-params
  - group: elarande-spoke1-ref
  - name: appName
    value: lms-functions-ref
  - name: parametersFileName
    value: ref.parameters.json

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: 'ubuntu-latest'

extends:
    template: templates/security/security-scans.yml@cet-iac
    parameters:
      steps:
        - template: templates/test/npm-test.yml@cet-iac
        
        - template: templates/function-app/update-function.yml@cet-iac
          parameters:
            parametersFileName: $(parametersFileName)
            appName: $(appName)
