trigger: none
pr: none

parameters:
  - name: generalParams
    type: string
    displayName: General params name (from library, <team-name>-general-params)
    default: elarande-general-params
  - name: spokeParams
    type: string
    displayName: Spoke params name (from library, <spoke-name>-<env>)
    default: elarande-spoke1-ref
  - name: parametersFileName
    type: string
    displayName: Parameters filename (from .azure folder, <env>.parameters.json)
    default: ref.parameters.json

variables:
  - group: ${{ parameters.generalParams }}
  - group: ${{ parameters.spokeParams }}

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/function-app/infra.yml@cet-iac
    parameters:
      location: $(location)
      parametersFileName: ${{ parameters.parametersFileName }}
