import { isRegistration } from "./index";

test("works?", () => {
  const result = isRegistration(
    `<ns0:courseOfferingRecord xmlns:ns0="http://www.imsglobal.org/services/lis/cmsv1p0/wsdl11/sync/imscms_v1p0"><ns0:sourcedGUID><ns0:sourcedId>77f7d9f2-7d2f-11ed-ba16-099432b5488e</ns0:sourcedId></ns0:sourcedGUID><ns0:courseOffering><ns0:label><ns0:language>sv-SE</ns0:language><ns0:textString>50620</ns0:textString></ns0:label><ns0:title><ns0:language>sv-SE</ns0:language><ns0:textString>SF1625</ns0:textString></ns0:title><ns0:parentTemplateId>7f315632-73d8-11e8-afa7-8e408e694e54</ns0:parentTemplateId><ns0:catalogDescription><ns0:shortDescription><ns0:language>sv-SE</ns0:language><ns0:textString>50620</ns0:textString></ns0:shortDescription><ns0:longDescription><ns0:language>sv-SE</ns0:language><ns0:textString>Envariabelanalys HT2023</ns0:textString></ns0:longDescription></ns0:catalogDescription><ns0:defaultCredits><ns0:language>sv-SE</ns0:language><ns0:textString>7.5</ns0:textString></ns0:defaultCredits><ns0:academicSession><ns0:language>sv-SE</ns0:language><ns0:textString>HT2023</ns0:textString></ns0:academicSession><ns0:org><ns0:orgUnit><ns0:language>sv-SE</ns0:language><ns0:textString>SF</ns0:textString></ns0:orgUnit><ns0:id><ns0:language>sv-SE</ns0:language><ns0:textString>ec22d024-73d6-11e8-8c58-f9aa7f7e4fb6</ns0:textString></ns0:id></ns0:org><ns0:timeFrame><ns0:begin>2023-08-28T00:00:00</ns0:begin><ns0:end>2023-10-27T00:00:00</ns0:end></ns0:timeFrame><ns0:extension><ns0:extensionNameVocabulary>LocallyDefined</ns0:extensionNameVocabulary><ns0:extensionTypeVocabulary>http://www.imsglobal.org/lis/cmsv1p0/extensionvocabularyv1p0</ns0:extensionTypeVocabulary><ns0:extensionField><ns0:fieldName>Tempo</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>Halvfart</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>TeachingTime</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>Dagtid</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>CourseTitle</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>Envariabelanalys</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>ParentTemplateCode</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>SF1625</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>Location</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>KTH Campus</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>OriginEvent</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>LADOK.AddReRegistration</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>ParentTemplateId</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>7f2659f8-73d8-11e8-b4e0-063f9afb40e3</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>TeachingTimeCode</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>DAG</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>TempoCode</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>50</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>TeachingTypeCode</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>NML</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>FinancingType</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>101050</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>CourseTitleEnglish</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>Calculus in One Variable</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>ParentTemplateDefaultCredits</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>7.5</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.locality.name</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>KTH Campus</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.level.name</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>Grundnivå</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.language.id</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>1</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.type.id</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>52</ns0:fieldValue></ns0:extensionField></ns0:extension></ns0:courseOffering></ns0:courseOfferingRecord>`
  );

  expect(result).toBeTruthy();
});

test("An AddRegistration message should be considered a registration of a student", () => {
  const result = isRegistration(`<ns0:membershipRecord
	xmlns:ns0="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0">
	<ns0:sourcedGUID>
		<ns0:sourcedId>0035b991-953c-11ec-823c-971220ed4206</ns0:sourcedId>
	</ns0:sourcedGUID>
	<ns0:membership>
		<ns0:collectionSourcedId>01137cb4-6251-11ec-bb6b-e957c4f74580</ns0:collectionSourcedId>
		<ns0:membershipIdType>courseOffering</ns0:membershipIdType>
		<ns0:member>
			<ns0:personSourcedId>704b782e-b573-11e7-96e6-896ca17746d1</ns0:personSourcedId>
			<ns0:role>
				<ns0:roleType>Learner</ns0:roleType>
				<ns0:status>Active</ns0:status>
				<ns0:extension>
					<ns0:extensionNameVocabulary>LocallyDefined</ns0:extensionNameVocabulary>
					<ns0:extensionTypeVocabulary>http://www.imsglobal.org/lis/cmsv1p0/extensionvocabularyv1p0</ns0:extensionTypeVocabulary>
					<ns0:extensionField>
						<ns0:fieldName>Admitted</ns0:fieldName>
						<ns0:fieldType>Boolean</ns0:fieldType>
						<ns0:fieldValue>true</ns0:fieldValue>
					</ns0:extensionField>
					<ns0:extensionField>
						<ns0:fieldName>Registered</ns0:fieldName>
						<ns0:fieldType>Boolean</ns0:fieldType>
						<ns0:fieldValue>true</ns0:fieldValue>
					</ns0:extensionField>
					<ns0:extensionField>
						<ns0:fieldName>Break</ns0:fieldName>
						<ns0:fieldType>Boolean</ns0:fieldType>
						<ns0:fieldValue>false</ns0:fieldValue>
					</ns0:extensionField>
					<ns0:extensionField>
						<ns0:fieldName>Dropout</ns0:fieldName>
						<ns0:fieldType>Boolean</ns0:fieldType>
						<ns0:fieldValue>false</ns0:fieldValue>
					</ns0:extensionField>
					<ns0:extensionField>
						<ns0:fieldName>OriginEvent</ns0:fieldName>
						<ns0:fieldType>string</ns0:fieldType>
						<ns0:fieldValue>LADOK.AddRegistration</ns0:fieldValue>
					</ns0:extensionField>
				</ns0:extension>
			</ns0:role>
		</ns0:member>
	</ns0:membership>
</ns0:membershipRecord>`);

  expect(result).toBeTruthy();
});

test("A Re-Registration message should be considered a registration of a student", () => {
  const result = isRegistration(`
<ns0:membershipRecord
	xmlns:ns0="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0">
	<ns0:sourcedGUID>
		<ns0:sourcedId>1374d1bb-5a95-11e8-9dae-241de8ab435c8280b0d7-626a-11ec-bb6b-e957c4f74580</ns0:sourcedId>
	</ns0:sourcedGUID>
	<ns0:membership>
		<ns0:collectionSourcedId>8280b0d7-626a-11ec-bb6b-e957c4f74580</ns0:collectionSourcedId>
		<ns0:membershipIdType>courseOffering</ns0:membershipIdType>
		<ns0:member>
			<ns0:personSourcedId>1374d1bb-5a95-11e8-9dae-241de8ab435c</ns0:personSourcedId>
			<ns0:role>
				<ns0:status>Active</ns0:status>
				<ns0:extension>
					<ns0:extensionNameVocabulary>LocallyDefined</ns0:extensionNameVocabulary>
					<ns0:extensionTypeVocabulary>http://www.imsglobal.org/lis/cmsv1p0/extensionvocabularyv1p0</ns0:extensionTypeVocabulary>
					<ns0:extensionField>
						<ns0:fieldName>Admitted</ns0:fieldName>
						<ns0:fieldType>Boolean</ns0:fieldType>
						<ns0:fieldValue>true</ns0:fieldValue>
					</ns0:extensionField>
					<ns0:extensionField>
						<ns0:fieldName>Registered</ns0:fieldName>
						<ns0:fieldType>Boolean</ns0:fieldType>
						<ns0:fieldValue>true</ns0:fieldValue>
					</ns0:extensionField>
					<ns0:extensionField>
						<ns0:fieldName>Break</ns0:fieldName>
						<ns0:fieldType>Boolean</ns0:fieldType>
						<ns0:fieldValue>false</ns0:fieldValue>
					</ns0:extensionField>
					<ns0:extensionField>
						<ns0:fieldName>Dropout</ns0:fieldName>
						<ns0:fieldType>Boolean</ns0:fieldType>
						<ns0:fieldValue>false</ns0:fieldValue>
					</ns0:extensionField>
					<ns0:extensionField>
						<ns0:fieldName>OriginEvent</ns0:fieldName>
						<ns0:fieldType>string</ns0:fieldType>
						<ns0:fieldValue>LADOK.AddReRegistration</ns0:fieldValue>
					</ns0:extensionField>
				</ns0:extension>
			</ns0:role>
		</ns0:member>
	</ns0:membership>
</ns0:membershipRecord>
                                `);

  expect(result).toBeTruthy();
});

test("This message should not make the app to crash", () => {
  const result = isRegistration(`
  <?xml version="1.0" encoding="UTF-8"?>
<ns0:personRecord xmlns:ns0="http://www.imsglobal.org/services/lis/pms2p0/wsdl11/sync/imspms_v2p0">
   <ns0:sourcedGUID>
      <ns0:sourcedId>d98a0d5f-b707-11ec-96e4-55918bf24e26</ns0:sourcedId>
   </ns0:sourcedGUID>
   <ns0:person>
      <ns0:name>
         <ns0:nameType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>FullName</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/nametypevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>FullName</ns0:textString>
            </ns0:instanceValue>
         </ns0:nameType>
         <ns0:partName>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>First</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>First</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Sven</ns0:textString>
            </ns0:instanceValue>
         </ns0:partName>
         <ns0:partName>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Last</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Last</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Svensson</ns0:textString>
            </ns0:instanceValue>
         </ns0:partName>
      </ns0:name>
      <ns0:address>
         <ns0:addressType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Temporary_Primary</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Temporary_Primary</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressType>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>NonfieldedStreetAddress1</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>NonfieldedStreetAddress1</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>KTH-vägen 0</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Postcode</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Postcode</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>00000</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>City</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>City</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Stockholm</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Country</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Country</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Sweden</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
      </ns0:address>
      <ns0:address>
         <ns0:addressType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Permanent_Primary</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Permanent_Primary</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressType>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>NonfieldedStreetAddress1</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>NonfieldedStreetAddress1</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>KTH-vägen 0</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Postcode</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Postcode</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>00000</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>City</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>City</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>STOCKHOLM</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Country</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Country</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Sverige</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
      </ns0:address>
      <ns0:contactinfo>
         <ns0:contactinfoType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>EmailPrimary</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/contactinfotypevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>EmailPrimary</ns0:textString>
            </ns0:instanceValue>
         </ns0:contactinfoType>
         <ns0:contactinfoValue>
            <ns0:language>sv-SE</ns0:language>
            <ns0:textString>SvenSvensson@kth.se</ns0:textString>
         </ns0:contactinfoValue>
      </ns0:contactinfo>
      <ns0:contactinfo>
         <ns0:contactinfoType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Mobile</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/contactinfotypevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Mobile</ns0:textString>
            </ns0:instanceValue>
         </ns0:contactinfoType>
         <ns0:contactinfoValue>
            <ns0:language>sv-SE</ns0:language>
            <ns0:textString>+46734870971</ns0:textString>
         </ns0:contactinfoValue>
      </ns0:contactinfo>
      <ns0:extension>
         <ns0:extensionNameVocabulary>LocallyDefined</ns0:extensionNameVocabulary>
         <ns0:extensionTypeVocabulary>http://www.imsglobal.org/lis/pmsv2p0/extensionvocabularyv1p0</ns0:extensionTypeVocabulary>
         <ns0:extensionField>
            <ns0:fieldName>PersonIdentityNumber</ns0:fieldName>
            <ns0:fieldType>string</ns0:fieldType>
            <ns0:fieldValue>1111111111111111</ns0:fieldValue>
         </ns0:extensionField>
         <ns0:extensionField>
            <ns0:fieldName>OriginEvent</ns0:fieldName>
            <ns0:fieldType>string</ns0:fieldType>
            <ns0:fieldValue>LADOK.AddAdmission</ns0:fieldValue>
         </ns0:extensionField>
         <ns0:extensionField>
            <ns0:fieldName>DeceasedFlag</ns0:fieldName>
            <ns0:fieldType>Boolean</ns0:fieldType>
            <ns0:fieldValue>false</ns0:fieldValue>
         </ns0:extensionField>
      </ns0:extension>
   </ns0:person>
</ns0:personRecord><?xml version="1.0" encoding="UTF-8"?>
<ns0:personRecord xmlns:ns0="http://www.imsglobal.org/services/lis/pms2p0/wsdl11/sync/imspms_v2p0">
   <ns0:sourcedGUID>
      <ns0:sourcedId>d98a0d5f-b707-11ec-96e4-55918bf24e26</ns0:sourcedId>
   </ns0:sourcedGUID>
   <ns0:person>
      <ns0:name>
         <ns0:nameType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>FullName</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/nametypevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>FullName</ns0:textString>
            </ns0:instanceValue>
         </ns0:nameType>
         <ns0:partName>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>First</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>First</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Sven</ns0:textString>
            </ns0:instanceValue>
         </ns0:partName>
         <ns0:partName>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Last</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Last</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Svensson</ns0:textString>
            </ns0:instanceValue>
         </ns0:partName>
      </ns0:name>
      <ns0:address>
         <ns0:addressType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Temporary_Primary</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Temporary_Primary</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressType>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>NonfieldedStreetAddress1</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>NonfieldedStreetAddress1</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>KTH-vägen 0</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Postcode</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Postcode</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>00000</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>City</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>City</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Stockholm</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Country</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Country</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Sweden</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
      </ns0:address>
      <ns0:address>
         <ns0:addressType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Permanent_Primary</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Permanent_Primary</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressType>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>NonfieldedStreetAddress1</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>NonfieldedStreetAddress1</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>KTH-vägen 0</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Postcode</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Postcode</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>00000</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>City</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>City</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>STOCKHOLM</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
         <ns0:addressPart>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Country</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/partnamevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceName>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Country</ns0:textString>
            </ns0:instanceName>
            <ns0:instanceValue>
               <ns0:language>sv-SE</ns0:language>
               <ns0:textString>Sverige</ns0:textString>
            </ns0:instanceValue>
         </ns0:addressPart>
      </ns0:address>
      <ns0:contactinfo>
         <ns0:contactinfoType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>EmailPrimary</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/contactinfotypevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>EmailPrimary</ns0:textString>
            </ns0:instanceValue>
         </ns0:contactinfoType>
         <ns0:contactinfoValue>
            <ns0:language>sv-SE</ns0:language>
            <ns0:textString>SvenSvensson@kth.se</ns0:textString>
         </ns0:contactinfoValue>
      </ns0:contactinfo>
      <ns0:contactinfo>
         <ns0:contactinfoType>
            <ns0:instanceIdentifier>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Mobile</ns0:textString>
            </ns0:instanceIdentifier>
            <ns0:instanceVocabulary>http://www.imsglobal.org/lis/pmsv2p0/contactinfotypevocabularyv1p0</ns0:instanceVocabulary>
            <ns0:instanceValue>
               <ns0:language>en-US</ns0:language>
               <ns0:textString>Mobile</ns0:textString>
            </ns0:instanceValue>
         </ns0:contactinfoType>
         <ns0:contactinfoValue>
            <ns0:language>sv-SE</ns0:language>
            <ns0:textString>+XXXXXXXXXXXX</ns0:textString>
         </ns0:contactinfoValue>
      </ns0:contactinfo>
      <ns0:extension>
         <ns0:extensionNameVocabulary>LocallyDefined</ns0:extensionNameVocabulary>
         <ns0:extensionTypeVocabulary>http://www.imsglobal.org/lis/pmsv2p0/extensionvocabularyv1p0</ns0:extensionTypeVocabulary>
         <ns0:extensionField>
            <ns0:fieldName>PersonIdentityNumber</ns0:fieldName>
            <ns0:fieldType>string</ns0:fieldType>
            <ns0:fieldValue>1111111111111111</ns0:fieldValue>
         </ns0:extensionField>
         <ns0:extensionField>
            <ns0:fieldName>OriginEvent</ns0:fieldName>
            <ns0:fieldType>string</ns0:fieldType>
            <ns0:fieldValue>LADOK.AddAdmission</ns0:fieldValue>
         </ns0:extensionField>
         <ns0:extensionField>
            <ns0:fieldName>DeceasedFlag</ns0:fieldName>
            <ns0:fieldType>Boolean</ns0:fieldType>
            <ns0:fieldValue>false</ns0:fieldValue>
         </ns0:extensionField>
      </ns0:extension>
   </ns0:person>
</ns0:personRecord>
	`);

  expect(result).toBeFalsy();
});

test("This should not crash (2)", () => {
  const result = isRegistration(
    `<ns0:membershipRecord xmlns:ns0="http://www.imsglobal.org/services/lis/mms2p0/wsdl11/sync/imsmms_v2p0"><ns0:sourcedGUID><ns0:sourcedId>1c909de8-b59a-11e7-96e6-896ca17746d10d4e304d-15a0-11ea-8191-b863e166428d</ns0:sourcedId></ns0:sourcedGUID><ns0:membership><ns0:collectionSourcedId>0d4e304d-15a0-11ea-8191-b863e166428d</ns0:collectionSourcedId><ns0:membershipIdType>courseOffering</ns0:membershipIdType><ns0:member><ns0:personSourcedId>1c909de8-b59a-11e7-96e6-896ca17746d1</ns0:personSourcedId><ns0:role><ns0:roleType>Learner</ns0:roleType><ns0:timeFrame><ns0:begin></ns0:begin><ns0:end></ns0:end></ns0:timeFrame><ns0:status>Active</ns0:status><ns0:extension><ns0:extensionNameVocabulary>LocallyDefined</ns0:extensionNameVocabulary><ns0:extensionTypeVocabulary>http://www.imsglobal.org/lis/cmsv1p0/extensionvocabularyv1p0</ns0:extensionTypeVocabulary><ns0:extensionField><ns0:fieldName>Admitted</ns0:fieldName><ns0:fieldType>Boolean</ns0:fieldType><ns0:fieldValue>true</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>Registered</ns0:fieldName><ns0:fieldType>Boolean</ns0:fieldType><ns0:fieldValue>true</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>Break</ns0:fieldName><ns0:fieldType>Boolean</ns0:fieldType><ns0:fieldValue>false</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>Dropout</ns0:fieldName><ns0:fieldType>Boolean</ns0:fieldType><ns0:fieldValue>false</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>OriginEvent</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>LADOK.AddRegistration</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>EarlyAccess</ns0:fieldName><ns0:fieldType>Boolean</ns0:fieldType><ns0:fieldValue>false</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>participation.program.code</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>TMAKM</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.is.root.packaging</ns0:fieldName><ns0:fieldType>Boolean</ns0:fieldType><ns0:fieldValue>false</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.is.latter.part</ns0:fieldName><ns0:fieldType>Boolean</ns0:fieldType><ns0:fieldValue>false</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.code</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>SF2955</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.instance.code</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>60851</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.uid</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>8153e819-73d8-11e8-afa7-8e408e694e54</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.version.uid</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>8164d849-73d8-11e8-afa7-8e408e694e54</ns0:fieldValue></ns0:extensionField><ns0:extensionField><ns0:fieldName>education.type.id</ns0:fieldName><ns0:fieldType>string</ns0:fieldType><ns0:fieldValue>52</ns0:fieldValue></ns0:extensionField></ns0:extension></ns0:role></ns0:member></ns0:membership></ns0:membershipRecord>`
  );

  expect(result).toBe(true);
});
